# Generated by Django 3.2.5 on 2022-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noPolls',
            field=models.IntegerField(default=0),
        ),
    ]
