# Generated by Django 3.2.5 on 2022-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='option',
            field=models.CharField(max_length=255),
        ),
    ]
